### ISSUE TITLE
ios WTArchitectView header missing

### ISSUE THREAD

**Issue by SzAkos** [brave-digital/react-native-wikitude#2]
Hey,

I've tried to use the package in my project. Successfully linked it.
In xCode I have an error about the WikitudeSDK/WTArchitectView.h is missing.

Should I manually install the WikitudeSDK.framework?

Thanks,
Akos

**Comment by FJLessing** [comment]
Hi Akos,

We will be pushing an update soon that will let you know how to include the Framework, but yes you would need to download the latest working SDK version, for my most recent build it was 7.2.0 that can be downloaded here : [Wikitude Javascript IOS SDK 7.2.0](https://cdn.wikitude.com/sdk/7_2_0/WikitudeSDK_iOS_7-2-0_2018-02-05_16-59-45.zip)

The **.framework** file needs to be put into the directory: `ios/RNWikitude/` or wherever your ` RNWikitude.xcodeproj` file is stored.

**Comment by SzAkos** [comment]
Hey,

Thanks for the answer. I've tried to put the framework manually inside /node_modules/react-native-wikitude/ios/RNWikitude folder. I did a clean in the project and tried to build it. 
Following error occured:

![screen shot 2018-07-23 at 17 46 58](https://user-images.githubusercontent.com/4680653/43087648-a8ef28d0-8ea0-11e8-9464-58c7a100f286.png)

Can you suggest something regarding this?
Thanks,
Akos

**Comment by SzAkos** [comment]
Hi,

Thanks for the update. But it seems the npm package hasn't been updated. 
I still get the error what I posted lately.

Any suggestions?
Akos

**Comment by CmerCy132** [comment]
I was able to run in the ios by adding : 

WikitudeSDK.framework in the Embeded Binaries

<img width="806" alt="screen shot 2018-08-15 at 3 14 12 pm" src="https://user-images.githubusercontent.com/36392135/44136064-f0e990b2-a09d-11e8-9f16-7fa6a3b4f981.png">

**Comment by SzAkos** [comment]
Thanks @CmerCy132 

I'm still struggling with it. This is the flow what I make:

npm i react-native-wikitude
Copy the framework under ./node_modules/react-native-wikitude/ios/RNWikitude/
react-native link react-native-wikitude
Build fails with the error above.

I've tried to add as an embedded binary.
Clean xcode project.
Build fails again.

Where is the mistake? :)

**Comment by CmerCy132** [comment]
On my end this is the flow that I did : 

npm i react-native-wikitude --save
react-native link react-native-wikitude
Copy the framework under ./node_modules/react-native-wikitude/ios/RNWikitude/

<img width="267" alt="screen shot 2018-08-16 at 12 10 12 am" src="https://user-images.githubusercontent.com/36392135/44158987-c7381b80-a0e8-11e8-8505-8344bec6b79a.png">

Added the WikitudeSDK.framework as an embedded binary

<img width="1003" alt="screen shot 2018-08-16 at 12 12 06 am" src="https://user-images.githubusercontent.com/36392135/44159125-10886b00-a0e9-11e8-9841-6f3c2da88bef.png">
